project:
  type: website

website:
  title: "Skyler Friedline"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - connect.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

