---
title: "About"
---

My career as a scientist was launched into motion at my 5th birthday when I received my first lab coat. After a very busy high school experience where I did well but felt quite lost, I began studying Biochemistry and Molecular Biology at the [University of California, Santa Barbara](https://www.mcdb.ucsb.edu/) with the intention of going to medical school. While pursuing my degree, I worked nights as an EMT with the local ambulance service and discovered that medicine was not going to be a sustainable career for me.

Upon graduation, I got a job with a brand-new biotech start-up launched by a professor I knew from UCSB. Here I discovered the joys of laboratory life and knew I had found something that felt like a good fit. As time went on, I realized that I believe preserving the environment on our planet is my highest priority, and decided to seek work more closely aligned with this value.

After 2 years at [Serimmune](https://serimmune.com/), I moved to the San Francisco Bay Area to work in the lab of [Adam Arkin](https://arkinlab.bio/) at the University of California, Berkeley. Here, I simultaneously served as the lab manager and conducted bioengineering research in the [Center for the Utilization of Biological Engineering in Space (CUBES)](https://cubes.space/). My projects during this time focused on how we can use microbial biotechnology to enable long-term life support for astronauts in space but also how we can think about our resources and wastes here on Earth as part of a circular economy.

After 2 years in this role, I decided it was time to further my education and moved to Vancouver, Canada to pursue graduate studies at the University of British Columbia. Over the next 3 years, I earned a M.Sc. in [Genome Science and Technology](https://www.gsat.ubc.ca/) under the co-supervision of [Prof. Steven Hallam](https://hallam.microbiology.ubc.ca/) (Department of Microbiology and Immunology) and [Assoc. Prof. Ryan Ziels](https://emberrlab.civil.ubc.ca/) (Department of Civil Engineering). My thesis work revolved around the idea that deepening our understanding of microbial communities can advance and improve our biological treatment and valorization of wastes. This project continues to form the basis of my work as I continue to serve as a research technician focused on microbial bioinformatics in the Ziels Lab.

Outside of the lab or away from the computer, I am eager to get outside. It is our beautiful planet that inspires my work, after all. British Columbia is a playground and I split my time between backpacking, skiing, surfing, kitesurfing, bike touring, tie-dyeing, and laying motionless on the beach.
